apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17-alpine
        ports:
          - containerPort: 80 
        
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-conf
            readOnly: true
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-index
            readOnly: true

      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx-conf
                path: nginx.conf 

 
        - name: nginx-index
          configMap:
            name: nginx-conf
            items:
              - key: nginx-index
                path: index.html
