apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-server
spec:
  selector:
      matchLabels:
        app: golang-server
        tier: golang
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-server
        tier: golang
    spec:
      containers:
      - name: golang
        image: soarescbm/golang-server-otimizada
        ports:
          - containerPort: 8000